window.PixelStrings = {
	playerIdle: [
		'. . . . . . . . . O O O O O O . . . . . . . . .',
		'. . . . . . . O O P P P P P P O O . . . . . . .',
		'. . . . . . O P P P P P P P P P P O . . . . . .',
		'. . . . . O P P P P P P P P P P P P O . . . . .',
		'. . . . . O P P P P P P P P P P P P O . . . . .',
		'. . . . O O P P P P P P P P P P P P O O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . . O P P P O O O O O O O P P O . . . . .',
		'. . . . . . O O O O B B B B B B O O O . . . . .',
		'. . . . . . . O B B B O B B O B O . . . . . . .',
		'. . . . . . . O B B B O B B O B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O O O O O O O O O O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .',
		'. . . . . . . O . . . . . . . . O . . . . . . .'
	],
	playerRunning: [
		'. . . . . . . . . O O O O O O . . . . . . . . .',
		'. . . . . . . O O P P P P P P O O . . . . . . .',
		'. . . . . . O P P P P P P P P P P O . . . . . .',
		'. . . . . O P P P P P P P P P P P P O . . . . .',
		'. . . . . O P P P P P P P P P P P P O . . . . .',
		'. . . . O O P P P P P P P P P P P P O O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . O P P P P P P P P P P P P P P O . . . .',
		'. . . . . O P P P O O O O O O O P P O . . . . .',
		'. . . . . . O O O O B B B B B B O O O . . . . .',
		'. . . . . . . O B B B O B B O B O . . . . . . .',
		'. . . . . . . O B B B O B B O B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'. . . . . . . O B B B B B B B B O . . . . . . .',
		'O O O O O O O O O O O O O O O O O O O O O O O O',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .',
		'. . . . . . . . . . . . . . . . . . . . . . . .'
	],
	enemyCap: [
		'. . . . . O O O O O O . . . . .',
		'. . . O O P P P P P P O O . . .',
		'. . O P P P P P P P P P P O . .',
		'. O P P P P P P P P P P P P O .',
		'. O P P P P P P P P P P P P O .',
		'O O P P P P P P P P P P P P O O',
		'O P P P P P P P P P P P P P P O',
		'O P P P P P P P P P P P P P P O',
		'O P P P P P P P P P P P P P P O',
		'O P P P P P P P P P P P P P P O',
		'. O P P P O O O O O O P P P O .',
		'. . O O O B O B B O B O O O . .',
		'. . . O B B O B B O B B O . . .'
	],
	enemyBody: [
		'. . . O B B B B B B B B O . . .'
	]
};
